### ISSUE TITLE
Wotlk Classic (Incoming damage - bug)

### ISSUE THREAD

**Issue by fahadlala01** [Witnesscm/xCT_Classic#10]
After configuring (incoming damage) to exclude (hide <player and icon>) it still shows the Icon and the Player (or source) of incoming damage. I can post screenshot or gif if needed (tested in solo as well as 5 man instance)

**Comment by Witnesscm** [comment]
I can’t reproduce this issue. If you want to disable the incoming damage frame, you just need to uncheck Enable in the frame settings.

**Comment by fahadlala01** [comment]
What you mentuon is correct .
What my point was that the incoming damage shows correctly but I wanted to
disable only the damage source like

Instead of
2.4k <falling>
4k <frozen orb>

Just show
2.4k
4k


Or thats not intended to be possible ?

**Comment by Witnesscm** [comment]
Do you mean you want to disable damage names and icons ?

Disable Icons:
  Incoming (Damage) - Icons - Enable Icons
Disable Names:
  Incoming (Damage) - Names, switch the damage source dropdown (Player/NPC/Environment), and change all name formats to None.

**Comment by fahadlala01** [comment]
Yes exactly this was intended.
(Disable Names:
Incoming (Damage) - Names, switch the damage source dropdown
(Player/NPC/Environment), and change all name formats to None.)

I had player nane format set to none.
But missed npc/environment name format setting

Now its all 100% working as intended. Sorry for hassle and invalid bug
report.

Thanks!
