### ISSUE TITLE
Spell Merged Additions - Holy Priest

### ISSUE THREAD

**Issue by volostyle** [Witnesscm/xCT_Classic#11]
Hi, can you please add Echo of Light, and Holy Word: Sanctuary to the Spell Merged options for Holy Priest?

**Comment by Witnesscm** [comment]
Of course, can you provide their spell IDs?  You can get IDs in game with the “Show Spell IDs” option enabled.

/xct - 'Spam Merger' - 'Merge Options' - 'Show Spell IDs'

**Comment by Witnesscm** [comment]
Added in [4.7.0](https://github.com/Witnesscm/xCT_Classic/releases/tag/4.7.0)
