### ISSUE TITLE
lua error on Alterac valley

### ISSUE THREAD

**Issue by Typhosy** [Witnesscm/xCT_Classic#2]
hi, when i config xct on AV poped my this error and cant move anything

6x FrameXML\StaticPopup.lua:5329: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: StaticPopup3:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@FrameXML\StaticPopup.lua"]:5329: in function `StaticPopup_SetUpAnchor'
[string "@FrameXML\StaticPopup.lua"]:5319: in function <FrameXML\StaticPopup.lua:5317>
[string "=[C]"]: ?
[string "=[C]"]: in function `StaticPopup_SetUpPosition'
[string "@FrameXML\StaticPopup.lua"]:4944: in function <FrameXML\StaticPopup.lua:4538>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `StaticPopup_Show'
[string "@xCT+\modules\frames.lua"]:1245: in function <xCT+\modules\frames.lua:1221>
[string "=[C]"]: ?
[string "@BuffOverlay\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-83.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
[string "@BuffOverlay\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-83.lua"]:836: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:657>
[string "=[C]"]: ?
[string "@Masque\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Masque\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Masque\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Masque\Libs\AceGUI-3.0-41\widgets\AceGUIWidget-Button.lua"]:22: in function <...sque\Libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>

**Comment by Witnesscm** [comment]
I cannot reproduce this error, and it seems to be caused by other addons such as make blizz popup dialog movable.
You can test again with only xCT+.
