### ISSUE TITLE
WOTLK PTR LUA ERROR

### ISSUE THREAD

**Issue by Typhosy** [Witnesscm/xCT_Classic#3]
2x xCT+/modules/combattext.lua:129: attempt to call global 'GetActiveSpecGroup' (a nil value)
[string "@xCT+/modules/combattext.lua"]:129: in function `UpdatePlayer'
[string "@xCT+/core.lua"]:123: in function <xCT+/core.lua:89>
[string "=[C]"]: ?
[string "@BuffOverlay/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ddOns/BuffOverlay/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@BuffOverlay/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@BuffOverlay/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...ddOns/BuffOverlay/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by Typhosy** [comment]
8x xCT+/modules/frames.lua:137: attempt to call method 'SetMinResize' (a nil value)
[string "@xCT+/modules/frames.lua"]:137: in function `UpdateFrames'
[string "@xCT+/core.lua"]:151: in function <xCT+/core.lua:149>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @BuffOverlay/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 runeIcons = <table> {
 }
 UpdateComboPointOptions = <function> defined @xCT+/core.lua:891
 OnSpamUpdate = <function> defined @xCT+/modules/frames.lua:600
 CombatStateChanged = <function> defined @xCT+/core.lua:1731
 MigratePrint = <function> defined @xCT+/core.lua:256
 EnableModule = <function> defined @BuffOverlay/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 RestoreAllDefaults = <function> defined @xCT+/modules/frames.lua:1264
 baseName = "xCT+"
 IterateEmbeds = <function> defined @BuffOverlay/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 specName = <table> {
 }
 EndConfigMode = <function> defined @xCT+/modules/frames.lua:915
 Clear = <function> defined @xCT+/modules/frames.lua:296
 Printf = <function> defined @BuffOverlay/Libs/AceConsole-3.0/AceConsole-3.0.lua:65
 CombatLogEvent = <function> defined @xCT+/modules/combattext.lua:1951
 SetDefaultModulePrototype = <function> defined @BuffOverlay/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 AddSpamMessage = <function> defined @xCT+/modules/frames.lua:497
 defaultModuleState = true
 IsEnabled = <function> defined @BuffOverlay/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 GenerateColorOptions = <function> defined @xCT+/core.lua:1561
 DisableModule = <function> defined @BuffOverlay/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 Abbreviate = <function> defined @xCT+/modules/frames.lua:333
 GetArgs = <function> defined @BuffOverlay/Libs/AceConsole-3.0/AceConsole-3.0.lua:140
 frames = <table> {
 }
 FrameTitles = <table> {
 }
 LoadAlignmentGrid = <function> defined @xCT+/modules/grid.lua:23
 db = <table> {
 }
 ToggleConfigMode = <function> defined @xCT+/modules/frames.lua:988
 QuickClassFrameUpdate = <function> defined @xCT+/modules/combattext.lua:731
 SetEnabledState = <function> defined @BuffOverlay/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 UpdateBlizzardFCT = <function> defined @xCT+/modules/blizzard.lua:79
 enabledState = true
 UpdateCombatTextEvents = <function> defined @xCT+/modules/combattext.lua:144
 EnableFrameScrolling = <function> defined @xCT+/modules/frames.lua:274
 OnCombatTextEvent = <function> defined @xCT+/modules/combattext.lua:545
 UpdatePlayer = <function> defined @xCT+/modules/combattext.lua:116
 IterateModules = <function> defined @BuffOverlay/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 events = <table> {
 }
 UpdateSpamSpells = <function> defined @xCT+/core.lua:525
 UpdateItemTypes = <function> defined @xCT+/core.lua:744
 combatEvents = Frame {
 }
 Enable = <function> defined @BuffOverlay/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @BuffOverlay/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 existingProfile = <table> {
 }
 TrackxCTCommand = <function> defined @xCT+/core.lua:1945
 HideConfigTool = <function> defined @xCT+/core.lua:1920
 DisableFrameScrolling = <function> defined @xCT+/modules/frames.lua:281
 ShowConfigTool = <function> defined @xCT+/core.lua:1862
 GetUnitAura = <function> defined @xCT+/modules/combattext.lua:2035
 OnAddonConfigRefreshed = <function> defined @xCT+/core.lua:1768
 defaultModuleLibraries = <table> {
 }
 player = <table> {
 }
 OpenxCTCommand = <function> defined @xCT+/core.lua:1777
 UnregisterChatCommand = <function> defined @BuffOverlay/Libs/AceConsole-3.0/AceConsole-3.0.lua:107
 RegisterChatCommand = <function> defined @BuffOve

**Comment by Witnesscm** [comment]
Fixed in 4.6.2
