### ISSUE TITLE
Not working with new wrath patch

### ISSUE THREAD

**Issue by jpgulliver** [Witnesscm/xCT_Classic#4]
The ulduar patch dropped, and this no longer is functioning. /xct does not pull up options, and combat text does not show

**Comment by jpgulliver** [comment]
![image](https://user-images.githubusercontent.com/13171800/213055243-62b30dc4-3c28-42b2-987e-04a9992ccf3a.png)

Many more errors, not just this one

**Comment by volostyle** [comment]
I noticed this as well. Please fix if you can, can't go back to MSBT!

EDIT- The files from 12/09 he posted actually work fine. I missed that before posting.

**Comment by Witnesscm** [comment]
This issue should have been fixed in 4.6.2.
Download from [Github Release](https://github.com/Witnesscm/xCT_Classic/releases) or use WowUp.
