### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by emiyowow** [Witnesscm/xCT_Classic#5]
Message: Interface/SharedXML/FontableFrameMixin.lua:22: bad argument #3 to 'SetFont' (Usage: self:SetFont(fontFile, height, flags))
Time: Thu Jan 19 15:13:19 2023
Count: 1
Stack: Interface/SharedXML/FontableFrameMixin.lua:22: bad argument #3 to 'SetFont' (Usage: self:SetFont(fontFile, height, flags))
[string "=[C]"]: in function `SetFont'
[string "@Interface/AddOns/xCT+/modules/frames.lua"]:218: in function `UpdateFrames'
[string "@Interface/AddOns/xCT+/modules/frames.lua"]:109: in function `GetFrame'
[string "@Interface/AddOns/xCT+/modules/frames.lua"]:1236: in function <Interface/AddOns/xCT+/modules/frames.lua:1225>
[string "=[C]"]: ?
[string "@Interface/AddOns/xCT+/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/xCT+/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@Interface/AddOns/xCT+/libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <Interface/AddOns/xCT+/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/xCT+/libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/xCT+/libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua"]:22: in function <...xCT+/libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

Locals: <none>
![Screenshot_1](https://user-images.githubusercontent.com/45388126/213445730-b82ca95d-2e06-41e5-b4f3-a2fc581b22c9.png)

having this issue

**Comment by emiyowow** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/45388126/213445550-4c0fd0a4-22ea-4ce4-a819-d78482f67aff.png)

**Comment by Witnesscm** [comment]
Fixed in 4.6.3
