### ISSUE TITLE
Patch Update

### ISSUE THREAD

**Issue by volostyle** [Witnesscm/xCT_Classic#9]
Hi, getting lots of errors after patch today.

8x xCT+/core.lua:1 (null)

6x Interface_Wrath\FrameXML\Bindings.xml:1 xCT+/core.lua:1 (null)

**Comment by Witnesscm** [comment]
I can’t reproduce this error on WotLK PTR. Are there any other errors? You can test again with only xCT+.

**Comment by volostyle** [comment]
So it seems that another addon is actually the cause of this. "Profession Master" is causing LUA errors in about 7 of my addons, including xct+. I'll reach out to the author and let them know. Thanks!
